#!/usr/bin/env ruby
# frozen_string_literal: true
require_relative "setup"

class Ls
  require "cmd"
  include Cmd

  set_banner usage: "ls [OPTIONS]",
             description: "Lists the contents of a directory"
  set_option "-g PATTERN", "--grep PATTERN", "A regular expression", as: Regexp
  set_option "-d PATH", "--directory PATH", "A path to a directory", as: String
  set_default grep: /.+/, directory: "/"

  def run
    options = parse_options(argv)
    options.help ? show_help : run_command(options)
  end

  private

  def run_command(options)
    puts Dir.entries(options.directory)
            .grep(options.grep)
            .sort
            .join("\n")
  end
end

##
# Run the command
Ls.new(ARGV).run
