#!/usr/bin/env ruby
# frozen_string_literal: true

class Ls
  require "cmd"
  include Cmd

  set_banner usage: "ls [OPTIONS]",
             description: "Lists the contents of a directory"
  set_option "-g PATTERN", "--grep PATTERN", "A regular expression", as: Regexp
  set_option "-p PATH", "--path PATH", "The target path", as: String
  set_default grep: /.+/, path: "/"

  def run
    options = parse!(argv)
    options.help ? show_help : run_command(options)
  end

  private

  def run_command(options)
    puts Dir.entries(options.path)
            .grep(options.grep)
            .sort
            .join("\n")
  end
end

##
# Run the command
Ls.new(ARGV).run
